{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"snowball_output\",\"customer\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "customer.customer_country": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer country": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_country": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "client country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_id"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "customer id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer id": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "id": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "id": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_id": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "client id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "customer.customer_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_name"
                  }
                },
                "NameType": "Name",
                "State": "Generated",
                "Terms": [
                  {
                    "customer name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer name": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "name": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "name": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_name": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer surname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "client name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_region "
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer region": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer region": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_region ": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "region": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "region": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_region": {
                      "State": "Generated",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "customer_region": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "customer location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "customer province": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "province": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "customer area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer district": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer zone": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer continent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "customer.dimension_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "dimension_1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dimension 1": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dimension 1": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "dimension_1": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball output": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball output": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "snowball_output": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "output": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "output": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "snowball production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "snowball productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "snowball yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.bop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "bop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bop arr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "bop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.cross_sell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "cross_sell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cross sell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "cross sell": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "cross_sell": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "sell": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sell": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "symbol sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "mark sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "sign sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "snowball_output.customer_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer churn": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "snowball_output.customer_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "snowball_output.eop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "eop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "eop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "eop arr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "eop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.grr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "grr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "grr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "grr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.measure": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "Measure"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "measure": {
                      "State": "Generated"
                    }
                  },
                  {
                    "measure": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "degree": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "quota": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "portion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "ration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "size": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.month_roll": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month_roll": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.7
                    }
                  },
                  {
                    "roll": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "mth roll": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "month reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.new_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "new_customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "new customer": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "new_customer": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "new client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "snowball_output.nrr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "nrr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nrr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "nrr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.period_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "period_type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "period type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "period type": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "period_type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "period category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period brand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "period class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "snowball_output.product_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product churn": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "product_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "snowball_output.product_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "product_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.snowball_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "snowball_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "snowball_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "essential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "snowball solution": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball explanation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball basis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  }
                ]
              },
              "snowball_output.total_bop": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "total_bop"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total bop": {
                      "State": "Generated"
                    }
                  },
                  {
                    "total bop": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "total_bop": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "bop": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "bop": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate bop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall bop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "total dance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "total boogie": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "total jive": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "total jig": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "dance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "boogie": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "jive": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "jig": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.upsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "upsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "upsell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "upsell": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "customer_has_customer_country": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_country"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_countries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_country": {
                    "Target": {
                      "Entity": "customer.customer_country"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_key": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_key"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_key": {
                    "Target": {
                      "Entity": "customer.customer_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_region": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_region"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_regions",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_region": {
                    "Target": {
                      "Entity": "customer.customer_region"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_dimension_1": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.dimension_1"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_dimension_1",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.dimension_1": {
                    "Target": {
                      "Entity": "customer.dimension_1"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_in_customer_country": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "ID": "customers_are_in_customer_countries",
                    "Preposition": {
                      "Object": {
                        "Role": "customer.customer_country"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_country": {
                    "Target": {
                      "Entity": "customer.customer_country"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "customer.customer_country"
                  }
                },
                "State": "Generated"
              },
              "customer_in_customer_region": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "ID": "customers_are_in_customer_regions",
                    "Preposition": {
                      "Object": {
                        "Role": "customer.customer_region"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_region": {
                    "Target": {
                      "Entity": "customer.customer_region"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "customer.customer_region"
                  }
                },
                "State": "Generated"
              },
              "customer_is_named_customer_id": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "ID": "customer_ids_are_names_IDs_of_customers",
                    "Name": {
                      "Name": {
                        "Role": "customer.customer_id"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_id"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_ids",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_id": {
                    "Target": {
                      "Entity": "customer.customer_id"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_is_named_customer_name": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "ID": "customer_names_are_names_IDs_of_customers",
                    "Name": {
                      "Name": {
                        "Role": "customer.customer_name"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_name"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_name": {
                    "Target": {
                      "Entity": "customer.customer_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_bop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.bop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_bop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.bop_arr": {
                    "Target": {
                      "Entity": "snowball_output.bop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_calendar": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "calendar"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_calendars",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output"
                      },
                      "Subject": {
                        "Role": "calendar"
                      }
                    },
                    "ID": "calendars_have_snowball_outputs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "calendar": {
                    "Target": {
                      "Entity": "calendar"
                    }
                  },
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_cross_sell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.cross_sell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_cross_sell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.cross_sell": {
                    "Target": {
                      "Entity": "snowball_output.cross_sell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_snowball_outputs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.customer_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customer_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.customer_churn": {
                    "Target": {
                      "Entity": "snowball_output.customer_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_downsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.downsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_downsells",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.downsell": {
                    "Target": {
                      "Entity": "snowball_output.downsell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_eop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.eop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_eop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.eop_arr": {
                    "Target": {
                      "Entity": "snowball_output.eop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_grr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.grr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_grrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.grr": {
                    "Target": {
                      "Entity": "snowball_output.grr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_measure": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.measure"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_measure",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.measure": {
                    "Target": {
                      "Entity": "snowball_output.measure"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_month_roll": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_month_rolls",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.month_roll": {
                    "Target": {
                      "Entity": "snowball_output.month_roll"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_new_customer": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.new_customer"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_new_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.new_customer": {
                    "Target": {
                      "Entity": "snowball_output.new_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_nrr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.nrr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_nrrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.nrr": {
                    "Target": {
                      "Entity": "snowball_output.nrr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_period_type": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.period_type"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_period_types",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.period_type": {
                    "Target": {
                      "Entity": "snowball_output.period_type"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_churn": {
                    "Target": {
                      "Entity": "snowball_output.product_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_key": {
                    "Target": {
                      "Entity": "snowball_output.product_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_snowball_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.snowball_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_snowball_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.snowball_key": {
                    "Target": {
                      "Entity": "snowball_output.snowball_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_total_bop": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.total_bop"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_total_bop",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.total_bop": {
                    "Target": {
                      "Entity": "snowball_output.total_bop"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_upsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.upsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_upsell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.upsell": {
                    "Target": {
                      "Entity": "snowball_output.upsell"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_507da38c-1dd2-4de0-95a1-7860b3c3f59b",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "customer_key",
        "fromTable": "snowball_output",
        "toColumn": "customer_key",
        "toTable": "customer"
      },
      {
        "name": "7e469495-ba5b-44e9-8dbc-bca2c155f17b",
        "fromColumn": "month_roll",
        "fromTable": "snowball_output",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0a25d77c-dcdd-44a7-989a-790f3a81aba0"
      },
      {
        "name": "3c2e7a36-9731-4afb-8f47-b52706778af9",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a1983d28-b279-4057-8286-f3a7ad947b90"
      },
      {
        "name": "d2f57038-bae7-4937-8961-f9bf1895e9ea",
        "fromColumn": "EOW - Saturday",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_330f0301-f7d4-42c4-8eb5-3dfb0656b605"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "snowball_output",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "snowball_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a526c146-8010-4476-9540-60e79f2abed1",
            "sourceColumn": "snowball_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "28909643-54f2-4e22-8fbf-a730f22e0a0e",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "product_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6a0cb17-a334-4e5f-96a7-610598c9ec5b",
            "sourceColumn": "product_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_roll",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "297df5f9-924c-46bb-ba12-b1bd44d5c9f8",
            "sourceColumn": "month_roll",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0a25d77c-dcdd-44a7-989a-790f3a81aba0"
                },
                "isDefault": true,
                "relationship": "7e469495-ba5b-44e9-8dbc-bca2c155f17b"
              }
            ]
          },
          {
            "name": "period_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "71bd2fe2-04da-4b20-8b85-a9ba6e4792f2",
            "sourceColumn": "period_type",
            "summarizeBy": "none"
          },
          {
            "name": "bop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "53ecde23-baa3-494c-b663-7d8440574278",
            "sourceColumn": "bop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "customer_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "996651f8-f16a-44aa-99da-c8f99883868e",
            "sourceColumn": "customer_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "product_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "f7d35c26-63f5-402b-a162-cf7e176d906b",
            "sourceColumn": "product_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "grr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "93905a52-93fe-49bc-8a04-87f01d8d3d95",
            "sourceColumn": "grr",
            "summarizeBy": "sum"
          },
          {
            "name": "upsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "6c234090-8e8b-4cbc-a22f-1c8f7f2381d1",
            "sourceColumn": "upsell",
            "summarizeBy": "sum"
          },
          {
            "name": "cross_sell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a796026d-65d1-49ae-8195-265f7143210a",
            "sourceColumn": "cross_sell",
            "summarizeBy": "sum"
          },
          {
            "name": "nrr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "f48d8405-b66c-43b3-bbd7-b57a352ac5a8",
            "sourceColumn": "nrr",
            "summarizeBy": "sum"
          },
          {
            "name": "new_customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "cdce1de2-c724-4a4e-8d9a-d1818de2e294",
            "sourceColumn": "new_customer",
            "summarizeBy": "sum"
          },
          {
            "name": "eop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "947998fc-a909-4130-a733-8f9579ac8f5c",
            "sourceColumn": "eop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "downsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "92e3efaa-5140-4df8-ad0d-a0c96ac60557",
            "sourceColumn": "downsell",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d76d33be-e695-43b1-9e35-836d3b461c41",
        "measures": [
          {
            "name": "total_bop",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SUM(snowball_output[bop_arr])",
            "lineageTag": "a71f0782-f21b-435f-a929-b5cfe632c89e"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "lineageTag": "559641c2-8170-4405-90bd-9275c7cd303a"
          },
          {
            "name": "Customer Retention %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Customers_Start = SUM(snowball_output[bop_arr])  ",
              "VAR Customers_End = SUM(snowball_output[grr])    ",
              "VAR Churned_Customers = SUM(snowball_output[customer_churn])",
              "RETURN",
              "DIVIDE(Customers_End - Churned_Customers, Customers_Start, 0) * 100",
              ""
            ],
            "lineageTag": "54969dae-d164-48ee-9352-afbe29a932ea"
          },
          {
            "name": "Customer Churn Percentage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Churned_Customers = SUM(snowball_output[customer_churn])  ",
              "VAR Customers_Start = SUM(snowball_output[bop_arr])           ",
              "RETURN",
              "DIVIDE(Churned_Customers, Customers_Start, 0) * 100",
              ""
            ],
            "lineageTag": "1d0f553a-88a0-44db-8551-3bed2d008515"
          },
          {
            "name": "New Customer Percenatge Increase",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR New_Customers = SUM(snowball_output[new_customer])   -- New customers during the period",
              "VAR Customers_Start = SUM(snowball_output[bop_arr])      -- Total customers at the start of the period",
              "RETURN",
              "DIVIDE(New_Customers, Customers_Start, 0) * 100"
            ],
            "lineageTag": "39988ce5-199b-48b8-a332-9d370aec3b80"
          },
          {
            "name": "Upsell %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Upsell_Value = SUM(snowball_output[upsell])   -- Total upsell during the period",
              "VAR Customers_Start = SUM(snowball_output[bop_arr])   -- Total customers at the start of the period",
              "RETURN",
              "DIVIDE(Upsell_Value, Customers_Start, 0) * 100",
              ""
            ],
            "lineageTag": "f4dfde76-0f2a-4100-b27f-3acf847fc7ea"
          },
          {
            "name": "Downsell Percentage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Downsell_Value = SUM(snowball_output[downsell])   -- Total downsell during the period",
              "VAR Customers_Start = SUM(snowball_output[bop_arr])   -- Total customers at the start of the period",
              "RETURN",
              "DIVIDE(Downsell_Value, Customers_Start, 0) * 100",
              ""
            ],
            "lineageTag": "84524ddd-5c99-4311-9e91-ae8dd082da7c"
          }
        ],
        "partitions": [
          {
            "name": "snowball_output",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\PardhuMahidhar\\Downloads\\snowball_output.csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"snowball_key\", type text}, {\"customer_key\", type text}, {\"product_key\", type text}, {\"month_roll\", type date}, {\"period_type\", type text}, {\"bop_arr\", type number}, {\"customer_churn\", type number}, {\"product_churn\", type number}, {\"downsell\", type number}, {\"grr\", type number}, {\"upsell\", type number}, {\"cross_sell\", Int64.Type}, {\"nrr\", type number}, {\"new_customer\", type number}, {\"eop_arr\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_81a4689f-f6c6-4caf-bedd-6cf4e5230dcb",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0bb8f98f-c3c8-437c-bdf3-e5158530a78f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "111f147a-2fff-412d-91a1-0061ef6433b6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c3929774-954b-475f-b866-265e53fd4a55",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9cfb977a-887b-49da-a540-b155ad6d64de",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1414d492-5749-48bd-8917-a201e0ae8169",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a012d2d6-8a6b-428a-aa6a-1573f481f938",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "662da054-367e-4d5c-99ad-2b2c20665a20",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fb92f0b5-ec33-4b8d-bddd-71708c4bf16e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e6ba85cc-d5ff-48ac-b308-c47f864d5407",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5117022c-356b-4cd6-8ff8-187923b0508c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c501eabd-6fa7-49a8-8695-5f9ae6d8e633",
                "ordinal": 3
              }
            ],
            "lineageTag": "07574250-3682-4a92-a494-7e2d40c34c4b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "d018bc8b-1c0b-4a7d-9e35-25932a904ebb",
        "partitions": [
          {
            "name": "DateTableTemplate_81a4689f-f6c6-4caf-bedd-6cf4e5230dcb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57fe6360-7696-408b-bba9-8a7571e37e42",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "51271bdd-0ab2-4f13-ab93-dc35b28b36cd",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "859515ac-2de9-4f59-a873-ffc5277d5d83",
            "sourceColumn": "customer_name",
            "summarizeBy": "none"
          },
          {
            "name": "customer_country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "675ea4e3-5ffe-43d6-b17e-ca604f7df825",
            "sourceColumn": "customer_country",
            "summarizeBy": "none"
          },
          {
            "name": "customer_region ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57b76985-586b-473a-b134-c3fd67624c87",
            "sourceColumn": "customer_region ",
            "summarizeBy": "none"
          },
          {
            "name": "dimension_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c346bef5-accf-4106-83ac-591c9aff0b82",
            "sourceColumn": "dimension_1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "91446e45-0067-4b70-a3ef-776379bda0e4",
        "partitions": [
          {
            "name": "customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\PardhuMahidhar\\Downloads\\customer.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_key\", type text}, {\"customer_id\", Int64.Type}, {\"customer_name\", type text}, {\"customer_country\", type text}, {\"customer_region \", type text}, {\"dimension_1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_0a25d77c-dcdd-44a7-989a-790f3a81aba0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cde68e16-a7d3-4ac2-b71e-89423604c813",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e40e64d9-ce35-496b-8bfc-7234b3df469c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2e07e3b6-a782-43c4-8189-dac399de2968",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "eaa1bdf3-d7cc-4a22-a6e9-76f0c2b31597",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "75e0bced-626c-4c00-b6c0-083779731bd7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3a3dfb87-be6f-47b6-8ba6-02b72020f640",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "aae1756b-ae15-426d-aad1-af3e600b8396",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "006f50b4-672b-4c4d-b333-b8f30c0d7bf2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "39196ab3-d196-4ac4-93e1-188d281eeebe",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1ec6e888-1bc4-4b60-8841-01f0c8586b6a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6de6788f-2729-4839-b5fc-abe460424c53",
                "ordinal": 3
              }
            ],
            "lineageTag": "2b626d73-8401-4c22-a72d-38a769cb0a1a"
          }
        ],
        "isHidden": true,
        "lineageTag": "e08b5164-5f20-455a-bd5b-ac7778f74bce",
        "partitions": [
          {
            "name": "LocalDateTable_0a25d77c-dcdd-44a7-989a-790f3a81aba0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('snowball_output'[month_roll])), 1, 1), Date(Year(MAX('snowball_output'[month_roll])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cd9aeeaea40b4dd0859a684b62d60ebb"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "981ff082-79fe-4e04-b686-a761d709c9cc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a1983d28-b279-4057-8286-f3a7ad947b90"
                },
                "isDefault": true,
                "relationship": "3c2e7a36-9731-4afb-8f47-b52706778af9"
              }
            ]
          },
          {
            "name": "DateAsInteger",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "094e28b4-803a-42ab-9045-a4fda0416129",
            "sourceColumn": "[DateAsInteger]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "78b39048-9ef5-46e1-a669-ddd3cabf997d",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year less 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "789115ac-5078-4fa2-a9a9-068b9edf628d",
            "sourceColumn": "[Year less 1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "685b757b-e5b7-464b-9098-c33dd486303b",
            "sourceColumn": "[MonthYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QuarterYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f84dfcda-597b-455b-aec5-4ba5e50763a0",
            "sourceColumn": "[QuarterYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2ffd888c-a239-47ea-8302-c7dabedde350",
            "sourceColumn": "[MonthNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6cf4a7e9-9828-475a-a539-8916fa782c7f",
            "sourceColumn": "[MonthText]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "02017f99-cda6-4dd3-836e-fb6551b367da",
            "sourceColumn": "[YearMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YMInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "35100c3e-eebd-4d30-887e-f5905094bb5f",
            "sourceColumn": "[YMInt]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekdayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "09311094-6f9f-4dd5-b2d3-c458ee722ec6",
            "sourceColumn": "[WeekdayNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year & Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "991ae89a-7702-4f2c-899a-742394b09892",
            "sourceColumn": "[Year & Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "85457327-ed80-4baf-a20c-1a1824baa93b",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "63ac84c7-faf8-460e-ac2f-cab26b59e01d",
            "sourceColumn": "[WeekNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "EOW - Saturday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "427a7b4d-97b0-45b6-8a3d-bfb6c55d579a",
            "sourceColumn": "[EOW - Saturday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_330f0301-f7d4-42c4-8eb5-3dfb0656b605"
                },
                "isDefault": true,
                "relationship": "d2f57038-bae7-4937-8961-f9bf1895e9ea"
              }
            ]
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "373e42b0-d5b3-4dda-99e2-5bd9a293ea15",
            "sourceColumn": "[Weekday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8bf9f055-c00a-4791-9196-4c1e443b50d8",
            "sourceColumn": "[DayNo]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8d99b682-e43a-4c81-b590-74b9c8d960ec",
            "sourceColumn": "[DayMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "37798fd9-aadb-433c-af06-0f349f8c5bef",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS(CALENDAR(date(2017,01,01),date(2026,12,31)),",
                "\"DateAsInteger\", FORMAT ( [Date], \"YYYYMMDD\" ), ",
                "\"Year\", FORMAT([Date], \"yyyy\"), ",
                "\"Year less 1\", FORMAT([Date], \"yyyy\")-1,",
                "\"MonthYear\", FORMAT([Date],\"mmm yy\"),",
                "\"QuarterYear\", FORMAT([Date],\"yyyy \\QQ\"), ",
                "\"MonthNo\", MONTH([Date]),",
                "\"MonthText\", FORMAT([Date], \"mmm\"),",
                "\"YearMonth\", FORMAT([Date], \"MMMM-YYYY\"),",
                "\"YMInt\", 13 * YEAR([Date]) + MONTH([Date]),",
                "\"WeekdayNo\", WEEKDAY([Date],2),",
                "\"Year & Month\", FORMAT([Date],\"MMM-YY\"),",
                "\"Month\", FORMAT([Date], \"mmmm\"), ",
                "\"WeekNo\", WEEKNUM([Date]),",
                "\"EOW - Saturday\", [Date]+7-WEEKDAY([Date]-7),",
                "\"Weekday\", FORMAT([Date], \"dddd\"), ",
                "\"DayNo\", FORMAT([Date], \"d\"),",
                "\"DayMonth\", FORMAT([Date], \"dd mmm\")",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a1983d28-b279-4057-8286-f3a7ad947b90",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "98fbb8ff-c2f9-49e8-8c44-cea8cc4f169a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "29ee311c-5e5d-48e1-a228-d66287eff5e8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a58746a9-43f7-4ce1-92c8-38eb891cae5c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ec346977-fe1a-4647-93ba-8f62a611ed39",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "15f4b031-8773-4dea-9cfa-b36dceaf923e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f860a729-2203-4c81-9164-541fc018fc02",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fe4ead2b-9098-43e3-a96a-66b5cca065cd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bbe3df5d-c1fc-4cbe-9997-c8346bbb0680",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f72ee584-1f74-4162-9b55-47a93cd17798",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "75d052c6-0e8e-481a-89a8-c8ecd1d2afcb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7b23482e-2ab3-4257-8939-88669c7b1e9d",
                "ordinal": 3
              }
            ],
            "lineageTag": "689b0931-c27e-4e27-b7e9-0bce466591c3"
          }
        ],
        "isHidden": true,
        "lineageTag": "6f993152-dace-4d9c-a2ef-f6af9b84d68b",
        "partitions": [
          {
            "name": "LocalDateTable_a1983d28-b279-4057-8286-f3a7ad947b90",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_330f0301-f7d4-42c4-8eb5-3dfb0656b605",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "babfe568-07ed-45d3-8ed0-afcfcd15ebd4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e27a6bf3-5205-4b79-b69a-f2fbf2545bfd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9b90e5a1-5e41-4649-92cf-f5a4198b2567",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "35b1c641-7f8b-4b42-81e8-d685e207c60a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e6e571d5-1cfc-4c71-b949-2e71e7727fe7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "41d2f328-a704-4828-991e-19f4820ea852",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "40c11be9-866b-4cc1-b790-c69b9e6ebefe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "212b7504-e88f-4b2d-8f19-1eba06b2815d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2e0d6e06-8b22-4efd-9f85-2b3850310e3a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "50bb44fa-ff9b-4c35-bf8b-af80926a38b5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7305fcfa-bc13-495a-9fb1-d0991f2fe66b",
                "ordinal": 3
              }
            ],
            "lineageTag": "b5dcc2eb-29da-4a5a-bf54-26fbc936faa7"
          }
        ],
        "isHidden": true,
        "lineageTag": "8bdfc165-a27a-4b1e-b784-bdb8315b5d0b",
        "partitions": [
          {
            "name": "LocalDateTable_330f0301-f7d4-42c4-8eb5-3dfb0656b605",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[EOW - Saturday])), 1, 1), Date(Year(MAX('Calendar'[EOW - Saturday])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}